### ISSUE TITLE
cd ops && sh make.sh && cd ..   got error CUDA version

### ISSUE THREAD

**Issue by JustinKai0527** [kodenii/Responsible-Visual-Editing#4]
raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError: 
The detected CUDA version (12.4) mismatches the version that was used to compile
PyTorch (11.8). Please make sure to use the same CUDA versions.

**Comment by LighteningDarkness** [comment]
Thank you for your interest to our work. It appears that there is an environment mismatch on your server, specifically between the CUDA version installed and the version required by PyTorch. To resolve this, you have two options:
- Reinstall a compatible version of PyTorch that matches your current CUDA version.
- Downgrade your CUDA version to match the requirements of your existing PyTorch installation.
We hope these suggestions help resolve the issue.
